server:
  port: 8081
  servlet:
    context-path:
spring:
  thymeleaf:
    encoding: utf-8
    mode: HTML
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: false
          paths: /*
  security:
    user:
      name: user
      password: 123456
  mvc:
    view:
      prefix: .html