server:
 port: 8081
 servlet:
   context-path:
spring:
  thymeleaf:
    encoding: utf-8
    mode: HTML
    prefix: classpath=/templates/,classpath=/public/src/
    suffix=: .html
    cache: false
  resources:
    chain:
      strategy:
        content:
          enabled: false
          paths: /*
  mvc:
    view:
      prefix: .html